services:
  postgres-users-db:
    image: postgres:15-alpine
    container_name: postgres-users-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: observatorio_ia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

    ports:
      - "5433:5432"

    volumes:
      - postgres_users_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d observatorio_ia"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_users_data: